### PR TITLE
Docker build works again

### PR DESCRIPTION
**Pull request by punkrokk**
Fixed Docker so it builds from scratch again. Published updated docker image.

### CODE REVIEW

**Comment by wzod** [comment]
Thanks for the pull request and bringing up the issue with pefile's download URL!  Currently working on automating docker builds and will incorporate your changes in a new pull request.

I should have the new pull request later today. If anything, please let me know.

**Comment by punkrokk** [comment]
My next "step" was going to be to setup an image on Docker Hub to auto build when there was an update to master branch. But that's not something I can do it looks like with out, A.) paying attention and forking, or b.) https://docs.docker.com/docker-hub/github/#linking-docker-hub-to-a-github-account. Happy to help out if you like.

**Comment by punkrokk** [comment]
Didn't mean to close the PR #59

**Comment by punkrokk** [comment]
reopening

**Comment by wzod** [comment]
Created PR #60, which includes the changes from PR #59, and created an automated build from Docker Hub to keep up with changes moving forward.

@punkrokk Let me know if this works and/or if I missed anything.

Hope this helps!

**Comment by punkrokk** [comment]
Wouldn't it make the most sense commit on top of my PR? Instead of making a new one that obsoletes mine? Also - the dockerhub only works when you update on your personal repo, not when fsf is pushed to master.

**Comment by punkrokk** [comment]
Also that way I can see what you changed and why.

**Comment by wzod** [comment]
I had a few other changes I needed to include with updating the Dockerfile including updating yara/yara-python along with pushing the automated build for FSF and figured it would be easier to include in one go. I included your changes in PR #60 to resolve the broken links to dependencies.

Regarding Docker Hub, I have a repository for automating the builds from GitHub (i.e. https://github.com/wzod/Dockerfiles ), which should now be a bit more streamlined now that the two are linked together.

Let me know if anything.

Thanks!

**Comment by jxb5151** [comment]
Closing since this was rolled into #60.

**Pull request closed without merging**
